"""Module 4: job ad generation, QR-code generation, and n8n-mediated
external portal distribution (LinkedIn/Indeed/Naukri/FacultyPlus). Actual
posting-to-portal logic lives in n8n's existing workflow -- this module only
builds the payload and calls it via N8nClient, exactly once, never directly
integrating an SDK for any of those portals."""

import io

import qrcode
from fastapi import Request
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.job_posting import JobPosting
from app.models.user import User
from app.services.n8n_client import N8nClient

# The portal codes the legacy distribute endpoint defaults to. Channels are
# rows in recruitment_channels now (migration e7f8a9b0c1d2 seeds these four
# with the same codes); this tuple only feeds DistributeRequest's default.
SUPPORTED_PORTALS: tuple[str, ...] = ("LINKEDIN", "INDEED", "NAUKRI", "FACULTYPLUS")


def build_public_apply_url(job_posting: JobPosting) -> str:
    return f"{settings.PUBLIC_APPLY_BASE_URL.rstrip('/')}/apply/{job_posting.public_apply_slug}"


def generate_job_ad(job_posting: JobPosting) -> dict:
    """Assembles ad fields from the VacancyRequest already reachable via
    job_posting.approved_vacancy.vacancy_request -- no AI call (the JD, if
    any, was already generated by Phase 3's generate-jd flow); falls back to
    a minimal templated body when jd_draft is empty."""
    vacancy_request = job_posting.approved_vacancy.vacancy_request
    body = vacancy_request.jd_draft or (
        f"{vacancy_request.position_title} ({vacancy_request.employment_type.value})\n"
        f"Qualification: {vacancy_request.qualification}\n"
        f"Experience: {vacancy_request.experience_required}"
    )
    return {
        "job_posting_id": job_posting.id,
        "position_title": vacancy_request.position_title,
        "campus_code": job_posting.campus.code,
        "employment_type": vacancy_request.employment_type.value,
        "role_category": vacancy_request.role_category.value,
        "qualification": vacancy_request.qualification,
        "experience_required": vacancy_request.experience_required,
        "body": body,
        "apply_url": build_public_apply_url(job_posting),
        "public_apply_slug": job_posting.public_apply_slug,
    }


def generate_qr_code_png(job_posting: JobPosting) -> bytes:
    """Generated on demand, never persisted -- same precedent as Phase 5's
    report exports not being written to MinIO."""
    image = qrcode.make(build_public_apply_url(job_posting))
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    return buf.getvalue()


def distribute_to_portals(
    db: Session,
    *,
    job_posting: JobPosting,
    portals: list[str],
    n8n_client: N8nClient,
    actor: User,
    request: Request | None,
) -> dict:
    """The original "post to these portals" call, kept for the existing
    button and n8n workflow. Since 2026-09-06 it is a thin wrapper over
    app/services/job_channels.py, which records a channel row per portal
    and one attempt per row -- see distribute_legacy there. Returns the
    service's {"ok": ...} dict; the ROUTER commits and then raises 502 on
    failure, so the attempt rows and the failure audit survive (they did
    not before: get_db never commits on an exception)."""
    from app.services import job_channels  # local: job_channels imports generate_job_ad from here

    return job_channels.distribute_legacy(
        db,
        job_posting=job_posting,
        portal_codes=portals,
        n8n_client=n8n_client,
        actor=actor,
        request=request,
    )
