"""Module 4: job ad generation, QR-code generation, and n8n-mediated
external portal distribution (LinkedIn/Indeed/Naukri/FacultyPlus). Actual
posting-to-portal logic lives in n8n's existing workflow -- this module only
builds the payload and calls it via N8nClient, exactly once, never directly
integrating an SDK for any of those portals."""

import io

import httpx
import qrcode
from fastapi import HTTPException, Request, status
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.job_posting import JobPosting
from app.models.user import User
from app.services.audit import log_event
from app.services.n8n_client import N8nClient

SUPPORTED_PORTALS: tuple[str, ...] = ("LINKEDIN", "INDEED", "NAUKRI", "FACULTYPLUS")


def build_public_apply_url(job_posting: JobPosting) -> str:
    return f"{settings.PUBLIC_APPLY_BASE_URL.rstrip('/')}/apply/{job_posting.public_apply_slug}"


def generate_job_ad(job_posting: JobPosting) -> dict:
    """Assembles ad fields from the VacancyRequest already reachable via
    job_posting.approved_vacancy.vacancy_request -- no AI call (the JD, if
    any, was already generated by Phase 3's generate-jd flow); falls back to
    a minimal templated body when jd_draft is empty."""
    vacancy_request = job_posting.approved_vacancy.vacancy_request
    body = vacancy_request.jd_draft or (
        f"{vacancy_request.position_title} ({vacancy_request.employment_type.value})\n"
        f"Qualification: {vacancy_request.qualification}\n"
        f"Experience: {vacancy_request.experience_required}"
    )
    return {
        "job_posting_id": job_posting.id,
        "position_title": vacancy_request.position_title,
        "campus_code": job_posting.campus.code,
        "employment_type": vacancy_request.employment_type.value,
        "role_category": vacancy_request.role_category.value,
        "qualification": vacancy_request.qualification,
        "experience_required": vacancy_request.experience_required,
        "body": body,
        "apply_url": build_public_apply_url(job_posting),
        "public_apply_slug": job_posting.public_apply_slug,
    }


def generate_qr_code_png(job_posting: JobPosting) -> bytes:
    """Generated on demand, never persisted -- same precedent as Phase 5's
    report exports not being written to MinIO."""
    image = qrcode.make(build_public_apply_url(job_posting))
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    return buf.getvalue()


def distribute_to_portals(
    db: Session,
    *,
    job_posting: JobPosting,
    portals: list[str],
    n8n_client: N8nClient,
    actor: User,
    request: Request | None,
) -> dict:
    invalid = [p for p in portals if p not in SUPPORTED_PORTALS]
    if invalid:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported portal(s): {', '.join(invalid)}. Supported: {', '.join(SUPPORTED_PORTALS)}.",
        )

    ad = generate_job_ad(job_posting)
    payload = {**ad, "job_posting_id": str(ad["job_posting_id"]), "portals": portals}

    try:
        n8n_response = n8n_client.post_webhook("job-distribution", payload)
    except httpx.HTTPError as exc:
        log_event(
            db,
            actor=actor,
            action="JOB_POSTING_DISTRIBUTE_FAILED",
            campus_context_id=job_posting.campus_id,
            entity_type="JobPosting",
            entity_id=job_posting.id,
            after_state={"portals": portals, "error": str(exc)},
            request=request,
        )
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY, detail="Failed to reach the job-distribution workflow"
        ) from exc

    log_event(
        db,
        actor=actor,
        action="JOB_POSTING_DISTRIBUTED",
        campus_context_id=job_posting.campus_id,
        entity_type="JobPosting",
        entity_id=job_posting.id,
        after_state={"portals": portals},
        request=request,
    )
    return {"portals": portals, "n8n_response": n8n_response}
