"""phase2_vacancy_pipeline_offers_joining

Revision ID: 08d365f809c1
Revises: 01d4d15b72c1
Create Date: 2026-07-12 16:02:18.404753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d365f809c1'
down_revision: Union[str, Sequence[str], None] = '01d4d15b72c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('resume_storage_key', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_table('vacancy_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('role_category', sa.Enum('TEACHING', 'NON_TEACHING', 'HOUSEKEEPING', name='staff_role_category_enum'), nullable=False),
    sa.Column('position_title', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='employment_type_enum'), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.Text(), nullable=False),
    sa.Column('experience_required', sa.String(length=100), nullable=False),
    sa.Column('salary_band_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_band_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('jd_draft', sa.Text(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='vacancy_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'DEAN_APPROVED', 'APPROVED', 'PUBLISHED', 'CLOSED', 'REJECTED', name='vacancy_request_status_enum'), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dean_reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('dean_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hr_reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('hr_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_id', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requested_count > 0', name=op.f('ck_vacancy_requests_requested_count_positive')),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_vacancy_requests_campus_id_campuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dean_reviewed_by_id'], ['users.id'], name=op.f('fk_vacancy_requests_dean_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_vacancy_requests_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hr_reviewed_by_id'], ['users.id'], name=op.f('fk_vacancy_requests_hr_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['users.id'], name=op.f('fk_vacancy_requests_rejected_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_vacancy_requests_requested_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancy_requests'))
    )
    op.create_index(op.f('ix_vacancy_requests_campus_id'), 'vacancy_requests', ['campus_id'], unique=False)
    op.create_index(op.f('ix_vacancy_requests_status'), 'vacancy_requests', ['status'], unique=False)
    op.create_table('approved_vacancies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vacancy_request_id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('total_positions', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_approved_vacancies_approved_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_approved_vacancies_campus_id_campuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vacancy_request_id'], ['vacancy_requests.id'], name=op.f('fk_approved_vacancies_vacancy_request_id_vacancy_requests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approved_vacancies')),
    sa.UniqueConstraint('vacancy_request_id', name=op.f('uq_approved_vacancies_vacancy_request_id'))
    )
    op.create_index(op.f('ix_approved_vacancies_campus_id'), 'approved_vacancies', ['campus_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('approved_vacancy_id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('public_apply_slug', sa.String(length=160), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_vacancy_id'], ['approved_vacancies.id'], name=op.f('fk_job_postings_approved_vacancy_id_approved_vacancies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_job_postings_campus_id_campuses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_postings')),
    sa.UniqueConstraint('approved_vacancy_id', name=op.f('uq_job_postings_approved_vacancy_id'))
    )
    op.create_index(op.f('ix_job_postings_campus_id'), 'job_postings', ['campus_id'], unique=False)
    op.create_index(op.f('ix_job_postings_public_apply_slug'), 'job_postings', ['public_apply_slug'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'SCREENING', 'ELIGIBLE', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'TECHNICAL_INTERVIEW', 'HR_INTERVIEW', 'SELECTED', 'OFFER_SENT', 'OFFER_ACCEPTED', 'JOINING_PENDING', 'JOINED', 'ONBOARDING_COMPLETE', 'EMPLOYEE_CREATED', 'REJECTED', name='application_status_enum'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_applications_campus_id_campuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_applications_candidate_id_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('fk_applications_job_posting_id_job_postings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_applications_recorded_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('candidate_id', 'job_posting_id', name='uq_application_candidate_posting')
    )
    op.create_index(op.f('ix_applications_campus_id'), 'applications', ['campus_id'], unique=False)
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_job_posting_id'), 'applications', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_employees_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_employees_campus_id_campuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('application_id', name=op.f('uq_employees_application_id'))
    )
    op.create_index(op.f('ix_employees_campus_id'), 'employees', ['campus_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_table('hiring_slots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('approved_vacancy_id', sa.UUID(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESERVED', 'FILLED', name='hiring_slot_status_enum'), nullable=False),
    sa.Column('reserved_application_id', sa.UUID(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_vacancy_id'], ['approved_vacancies.id'], name=op.f('fk_hiring_slots_approved_vacancy_id_approved_vacancies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reserved_application_id'], ['applications.id'], name=op.f('fk_hiring_slots_reserved_application_id_applications'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hiring_slots')),
    sa.UniqueConstraint('approved_vacancy_id', 'slot_number', name='uq_hiring_slot_vacancy_number')
    )
    op.create_index(op.f('ix_hiring_slots_approved_vacancy_id'), 'hiring_slots', ['approved_vacancy_id'], unique=False)
    op.create_index(op.f('ix_hiring_slots_reserved_application_id'), 'hiring_slots', ['reserved_application_id'], unique=False)
    op.create_index(op.f('ix_hiring_slots_status'), 'hiring_slots', ['status'], unique=False)
    op.create_index('uq_hiring_slot_reserved_application', 'hiring_slots', ['reserved_application_id'], unique=True, postgresql_where='reserved_application_id IS NOT NULL')
    op.create_table('joining_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', name='joining_document_status_enum'), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_joining_documents_application_id_applications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_joining_documents')),
    sa.UniqueConstraint('application_id', 'document_type', name='uq_joining_document_application_type')
    )
    op.create_index(op.f('ix_joining_documents_application_id'), 'joining_documents', ['application_id'], unique=False)
    op.create_table('joining_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('actual_joining_date', sa.Date(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_joining_records_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['onboarding_completed_by_id'], ['users.id'], name=op.f('fk_joining_records_onboarding_completed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_joining_records')),
    sa.UniqueConstraint('application_id', name=op.f('uq_joining_records_application_id'))
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('offered_by_id', sa.UUID(), nullable=False),
    sa.Column('salary_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salary_currency', sa.String(length=3), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'WITHDRAWN', name='offer_status_enum'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_offers_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offered_by_id'], ['users.id'], name=op.f('fk_offers_offered_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index(op.f('ix_offers_application_id'), 'offers', ['application_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_application_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_table('joining_records')
    op.drop_index(op.f('ix_joining_documents_application_id'), table_name='joining_documents')
    op.drop_table('joining_documents')
    op.drop_index('uq_hiring_slot_reserved_application', table_name='hiring_slots', postgresql_where='reserved_application_id IS NOT NULL')
    op.drop_index(op.f('ix_hiring_slots_status'), table_name='hiring_slots')
    op.drop_index(op.f('ix_hiring_slots_reserved_application_id'), table_name='hiring_slots')
    op.drop_index(op.f('ix_hiring_slots_approved_vacancy_id'), table_name='hiring_slots')
    op.drop_table('hiring_slots')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_campus_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_posting_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_campus_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_job_postings_public_apply_slug'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_campus_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_approved_vacancies_campus_id'), table_name='approved_vacancies')
    op.drop_table('approved_vacancies')
    op.drop_index(op.f('ix_vacancy_requests_status'), table_name='vacancy_requests')
    op.drop_index(op.f('ix_vacancy_requests_campus_id'), table_name='vacancy_requests')
    op.drop_table('vacancy_requests')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###

    # Autogenerate doesn't emit DROP TYPE for enums created inline on a
    # column (DROP TABLE doesn't drop the associated Postgres enum type) --
    # without these, re-running upgrade() after a downgrade fails with
    # "type already exists". Same latent gap exists in Phase 1's migration;
    # fixed here for all Phase 2 enums.
    bind = op.get_bind()
    sa.Enum(name="offer_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="joining_document_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="hiring_slot_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="application_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="vacancy_request_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="vacancy_priority_enum").drop(bind, checkfirst=True)
    sa.Enum(name="employment_type_enum").drop(bind, checkfirst=True)
    sa.Enum(name="staff_role_category_enum").drop(bind, checkfirst=True)
