"""phase3_ai_agents_interviews_notifications

Revision ID: 7a4915280966
Revises: 08d365f809c1
Create Date: 2026-07-12 20:16:03.671844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4915280966'
down_revision: Union[str, Sequence[str], None] = '08d365f809c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('campus_context_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'TELEGRAM', 'SMS', 'WHATSAPP', name='notification_channel_enum'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status_enum'), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('recipient_user_id IS NOT NULL OR recipient_email IS NOT NULL', name=op.f('ck_notifications_has_recipient')),
    sa.ForeignKeyConstraint(['campus_context_id'], ['campuses.id'], name=op.f('fk_notifications_campus_context_id_campuses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_campus_context_id'), 'notifications', ['campus_context_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_entity_type'), 'notifications', ['related_entity_type'], unique=False)
    op.create_table('interview_schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('interview_type', sa.Enum('TECHNICAL', 'HR', 'TEACHING_DEMO', 'GENERAL', name='interview_type_enum'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='interview_schedule_status_enum'), nullable=False),
    sa.Column('scheduled_by_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_interview_schedules_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_interview_schedules_campus_id_campuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_by_id'], ['users.id'], name=op.f('fk_interview_schedules_scheduled_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_schedules'))
    )
    op.create_index(op.f('ix_interview_schedules_application_id'), 'interview_schedules', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_schedules_campus_id'), 'interview_schedules', ['campus_id'], unique=False)
    op.create_index(op.f('ix_interview_schedules_status'), 'interview_schedules', ['status'], unique=False)
    op.create_table('resume_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('eligibility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('skill_match_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('qualification_match_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('experience_match_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('publication_count', sa.Integer(), nullable=True),
    sa.Column('overall_recruitment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('semantic_similarity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('extracted_skills', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('extracted_qualification', sa.Text(), nullable=True),
    sa.Column('extracted_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_candidate_id', sa.UUID(), nullable=True),
    sa.Column('is_incomplete_profile', sa.Boolean(), nullable=False),
    sa.Column('incomplete_reasons', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('screened_by_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_resume_scores_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['duplicate_of_candidate_id'], ['candidates.id'], name=op.f('fk_resume_scores_duplicate_of_candidate_id_candidates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screened_by_id'], ['users.id'], name=op.f('fk_resume_scores_screened_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_scores'))
    )
    op.create_index(op.f('ix_resume_scores_application_id'), 'resume_scores', ['application_id'], unique=True)
    op.create_index(op.f('ix_resume_scores_overall_recruitment_score'), 'resume_scores', ['overall_recruitment_score'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('interview_schedule_id', sa.UUID(), nullable=False),
    sa.Column('panel_member_id', sa.UUID(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('research_score', sa.Integer(), nullable=True),
    sa.Column('teaching_demo_score', sa.Integer(), nullable=True),
    sa.Column('overall_recommendation', sa.Enum('STRONG_HIRE', 'HIRE', 'NO_HIRE', 'STRONG_NO_HIRE', name='interview_recommendation_enum'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('communication_score IS NULL OR communication_score BETWEEN 1 AND 10', name=op.f('ck_interview_feedback_communication_score_range')),
    sa.CheckConstraint('research_score IS NULL OR research_score BETWEEN 1 AND 10', name=op.f('ck_interview_feedback_research_score_range')),
    sa.CheckConstraint('teaching_demo_score IS NULL OR teaching_demo_score BETWEEN 1 AND 10', name=op.f('ck_interview_feedback_teaching_demo_score_range')),
    sa.CheckConstraint('technical_score IS NULL OR technical_score BETWEEN 1 AND 10', name=op.f('ck_interview_feedback_technical_score_range')),
    sa.ForeignKeyConstraint(['interview_schedule_id'], ['interview_schedules.id'], name=op.f('fk_interview_feedback_interview_schedule_id_interview_schedules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['panel_member_id'], ['users.id'], name=op.f('fk_interview_feedback_panel_member_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_feedback')),
    sa.UniqueConstraint('interview_schedule_id', 'panel_member_id', name='uq_feedback_schedule_member')
    )
    op.create_index(op.f('ix_interview_feedback_interview_schedule_id'), 'interview_feedback', ['interview_schedule_id'], unique=False)
    op.create_index(op.f('ix_interview_feedback_panel_member_id'), 'interview_feedback', ['panel_member_id'], unique=False)
    op.create_table('interview_panel_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('interview_schedule_id', sa.UUID(), nullable=False),
    sa.Column('panel_member_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_schedule_id'], ['interview_schedules.id'], name=op.f('fk_interview_panel_assignments_interview_schedule_id_interview_schedules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['panel_member_id'], ['users.id'], name=op.f('fk_interview_panel_assignments_panel_member_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_panel_assignments')),
    sa.UniqueConstraint('interview_schedule_id', 'panel_member_id', name='uq_panel_assignment_schedule_member')
    )
    op.create_index(op.f('ix_interview_panel_assignments_interview_schedule_id'), 'interview_panel_assignments', ['interview_schedule_id'], unique=False)
    op.create_index(op.f('ix_interview_panel_assignments_panel_member_id'), 'interview_panel_assignments', ['panel_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_panel_assignments_panel_member_id'), table_name='interview_panel_assignments')
    op.drop_index(op.f('ix_interview_panel_assignments_interview_schedule_id'), table_name='interview_panel_assignments')
    op.drop_table('interview_panel_assignments')
    op.drop_index(op.f('ix_interview_feedback_panel_member_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_interview_schedule_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_resume_scores_overall_recruitment_score'), table_name='resume_scores')
    op.drop_index(op.f('ix_resume_scores_application_id'), table_name='resume_scores')
    op.drop_table('resume_scores')
    op.drop_index(op.f('ix_interview_schedules_status'), table_name='interview_schedules')
    op.drop_index(op.f('ix_interview_schedules_campus_id'), table_name='interview_schedules')
    op.drop_index(op.f('ix_interview_schedules_application_id'), table_name='interview_schedules')
    op.drop_table('interview_schedules')
    op.drop_index(op.f('ix_notifications_related_entity_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_campus_context_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

    # Autogenerate doesn't emit DROP TYPE for enums created inline on a
    # column -- without these, re-running upgrade() after a downgrade fails
    # with "type already exists" (same fix applied to the Phase 2 migration).
    bind = op.get_bind()
    sa.Enum(name="interview_recommendation_enum").drop(bind, checkfirst=True)
    sa.Enum(name="interview_schedule_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="interview_type_enum").drop(bind, checkfirst=True)
    sa.Enum(name="notification_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="notification_channel_enum").drop(bind, checkfirst=True)
